export const forecast = [
  //   {
  //     Headline: {
  //       EffectiveDate: "2022-01-13T19:00:00+02:00",
  //       EffectiveEpochDate: 1642093200,
  //       Severity: 3,
  //       Text: "Expect showers Thursday evening",
  //       Category: "rain",
  //       EndDate: "2022-01-14T01:00:00+02:00",
  //       EndEpochDate: 1642114800,
  //       MobileLink:
  //         "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?unit=c&lang=en-us",
  //       Link: "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?unit=c&lang=en-us",
  //     },
  // DailyForecasts: [
  {
    Date: "2022-01-12T07:00:00+02:00",
    EpochDate: 1641963600,
    Sun: {
      Rise: "2022-01-12T06:43:00+02:00",
      EpochRise: 1641962580,
      Set: "2022-01-12T16:56:00+02:00",
      EpochSet: 1641999360,
    },
    Moon: {
      Rise: "2022-01-12T12:47:00+02:00",
      EpochRise: 1641984420,
      Set: "2022-01-13T02:49:00+02:00",
      EpochSet: 1642034940,
      Phase: "WaxingGibbous",
      Age: 10,
    },
    Temperature: {
      Minimum: {
        Value: 13.1,
        Unit: "C",
        UnitType: 17,
      },
      Maximum: {
        Value: 21.8,
        Unit: "C",
        UnitType: 17,
      },
    },
    RealFeelTemperature: {
      Minimum: {
        Value: 12.8,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
      Maximum: {
        Value: 21.4,
        Unit: "C",
        UnitType: 17,
        Phrase: "Pleasant",
      },
    },
    RealFeelTemperatureShade: {
      Minimum: {
        Value: 12.8,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
      Maximum: {
        Value: 20,
        Unit: "C",
        UnitType: 17,
        Phrase: "Pleasant",
      },
    },
    HoursOfSun: 5.7,
    DegreeDaySummary: {
      Heating: {
        Value: 1,
        Unit: "C",
        UnitType: 17,
      },
      Cooling: {
        Value: 0,
        Unit: "C",
        UnitType: 17,
      },
    },
    AirAndPollen: [
      {
        Name: "AirQuality",
        Value: 0,
        Category: "Good",
        CategoryValue: 1,
        Type: "Ozone",
      },
      {
        Name: "Grass",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Mold",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Ragweed",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Tree",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "UVIndex",
        Value: 2,
        Category: "Low",
        CategoryValue: 1,
      },
    ],
    Day: {
      Icon: 4,
      IconPhrase: "Intermittent clouds",
      HasPrecipitation: false,
      ShortPhrase: "Pleasant with clouds and sun",
      LongPhrase: "Pleasant with times of clouds and sun",
      PrecipitationProbability: 1,
      ThunderstormProbability: 0,
      RainProbability: 1,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 13,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 206,
          Localized: "SSW",
          English: "SSW",
        },
      },
      WindGust: {
        Speed: {
          Value: 31.5,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 99,
          Localized: "E",
          English: "E",
        },
      },
      TotalLiquid: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 0,
      HoursOfRain: 0,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 52,
      Evapotranspiration: {
        Value: 0.1,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 4667.6,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Night: {
      Icon: 38,
      IconPhrase: "Mostly cloudy",
      HasPrecipitation: false,
      ShortPhrase: "Increasing clouds",
      LongPhrase: "Increasing clouds",
      PrecipitationProbability: 3,
      ThunderstormProbability: 0,
      RainProbability: 3,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 7.4,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 169,
          Localized: "S",
          English: "S",
        },
      },
      WindGust: {
        Speed: {
          Value: 22.2,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 162,
          Localized: "SSE",
          English: "SSE",
        },
      },
      TotalLiquid: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 0,
      HoursOfRain: 0,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 79,
      Evapotranspiration: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 0,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Sources: ["AccuWeather"],
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=1&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=1&unit=c&lang=en-us",
  },
  {
    Date: "2022-01-13T07:00:00+02:00",
    EpochDate: 1642050000,
    Sun: {
      Rise: "2022-01-13T06:42:00+02:00",
      EpochRise: 1642048920,
      Set: "2022-01-13T16:57:00+02:00",
      EpochSet: 1642085820,
    },
    Moon: {
      Rise: "2022-01-13T13:21:00+02:00",
      EpochRise: 1642072860,
      Set: "2022-01-14T03:46:00+02:00",
      EpochSet: 1642124760,
      Phase: "WaxingGibbous",
      Age: 11,
    },
    Temperature: {
      Minimum: {
        Value: 11.7,
        Unit: "C",
        UnitType: 17,
      },
      Maximum: {
        Value: 18.2,
        Unit: "C",
        UnitType: 17,
      },
    },
    RealFeelTemperature: {
      Minimum: {
        Value: 7.6,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 17.8,
        Unit: "C",
        UnitType: 17,
        Phrase: "Pleasant",
      },
    },
    RealFeelTemperatureShade: {
      Minimum: {
        Value: 7.6,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 15.9,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    HoursOfSun: 5,
    DegreeDaySummary: {
      Heating: {
        Value: 3,
        Unit: "C",
        UnitType: 17,
      },
      Cooling: {
        Value: 0,
        Unit: "C",
        UnitType: 17,
      },
    },
    AirAndPollen: [
      {
        Name: "AirQuality",
        Value: 0,
        Category: "Good",
        CategoryValue: 1,
        Type: "Ozone",
      },
      {
        Name: "Grass",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Mold",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Ragweed",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Tree",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "UVIndex",
        Value: 3,
        Category: "Moderate",
        CategoryValue: 2,
      },
    ],
    Day: {
      Icon: 4,
      IconPhrase: "Intermittent clouds",
      HasPrecipitation: false,
      ShortPhrase: "Sun and clouds",
      LongPhrase: "Sun and clouds",
      PrecipitationProbability: 25,
      ThunderstormProbability: 0,
      RainProbability: 25,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 18.5,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 216,
          Localized: "SW",
          English: "SW",
        },
      },
      WindGust: {
        Speed: {
          Value: 38.9,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 234,
          Localized: "SW",
          English: "SW",
        },
      },
      TotalLiquid: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 0,
      HoursOfRain: 0,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 62,
      Evapotranspiration: {
        Value: 0.1,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 5752.5,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Night: {
      Icon: 12,
      IconPhrase: "Showers",
      HasPrecipitation: true,
      PrecipitationType: "Rain",
      PrecipitationIntensity: "Heavy",
      ShortPhrase: "Downpours early; cloudy",
      LongPhrase: "Heavy showers in the evening; cloudy",
      PrecipitationProbability: 98,
      ThunderstormProbability: 20,
      RainProbability: 98,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 20.4,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 251,
          Localized: "WSW",
          English: "WSW",
        },
      },
      WindGust: {
        Speed: {
          Value: 35.2,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 252,
          Localized: "WSW",
          English: "WSW",
        },
      },
      TotalLiquid: {
        Value: 35.7,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 35.7,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 3,
      HoursOfRain: 3,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 79,
      Evapotranspiration: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 0,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Sources: ["AccuWeather"],
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=2&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=2&unit=c&lang=en-us",
  },
  {
    Date: "2022-01-14T07:00:00+02:00",
    EpochDate: 1642136400,
    Sun: {
      Rise: "2022-01-14T06:42:00+02:00",
      EpochRise: 1642135320,
      Set: "2022-01-14T16:58:00+02:00",
      EpochSet: 1642172280,
    },
    Moon: {
      Rise: "2022-01-14T14:00:00+02:00",
      EpochRise: 1642161600,
      Set: "2022-01-15T04:41:00+02:00",
      EpochSet: 1642214460,
      Phase: "WaxingGibbous",
      Age: 12,
    },
    Temperature: {
      Minimum: {
        Value: 10.1,
        Unit: "C",
        UnitType: 17,
      },
      Maximum: {
        Value: 15.1,
        Unit: "C",
        UnitType: 17,
      },
    },
    RealFeelTemperature: {
      Minimum: {
        Value: 8,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 12.2,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    RealFeelTemperatureShade: {
      Minimum: {
        Value: 8,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 12.2,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    HoursOfSun: 3.2,
    DegreeDaySummary: {
      Heating: {
        Value: 5,
        Unit: "C",
        UnitType: 17,
      },
      Cooling: {
        Value: 0,
        Unit: "C",
        UnitType: 17,
      },
    },
    AirAndPollen: [
      {
        Name: "AirQuality",
        Value: 0,
        Category: "Good",
        CategoryValue: 1,
        Type: "Ozone",
      },
      {
        Name: "Grass",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Mold",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Ragweed",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Tree",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "UVIndex",
        Value: 1,
        Category: "Low",
        CategoryValue: 1,
      },
    ],
    Day: {
      Icon: 12,
      IconPhrase: "Showers",
      HasPrecipitation: true,
      PrecipitationType: "Rain",
      PrecipitationIntensity: "Heavy",
      ShortPhrase: "Clouds, downpours in the p.m.",
      LongPhrase: "Overcast with heavy showers in the afternoon",
      PrecipitationProbability: 100,
      ThunderstormProbability: 20,
      RainProbability: 100,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 20.4,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 271,
          Localized: "W",
          English: "W",
        },
      },
      WindGust: {
        Speed: {
          Value: 37,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 271,
          Localized: "W",
          English: "W",
        },
      },
      TotalLiquid: {
        Value: 47.5,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 47.5,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 4,
      HoursOfRain: 4,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 78,
      Evapotranspiration: {
        Value: 0.1,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 4302,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Night: {
      Icon: 40,
      IconPhrase: "Mostly cloudy w/ showers",
      HasPrecipitation: true,
      PrecipitationType: "Rain",
      PrecipitationIntensity: "Moderate",
      ShortPhrase: "Mostly cloudy with showers",
      LongPhrase: "Mostly cloudy with showers",
      PrecipitationProbability: 94,
      ThunderstormProbability: 19,
      RainProbability: 94,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 14.8,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 236,
          Localized: "SW",
          English: "SW",
        },
      },
      WindGust: {
        Speed: {
          Value: 25.9,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 236,
          Localized: "SW",
          English: "SW",
        },
      },
      TotalLiquid: {
        Value: 11.8,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 11.8,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 6,
      HoursOfRain: 6,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 70,
      Evapotranspiration: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 0,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Sources: ["AccuWeather"],
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=3&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=3&unit=c&lang=en-us",
  },
  {
    Date: "2022-01-15T07:00:00+02:00",
    EpochDate: 1642222800,
    Sun: {
      Rise: "2022-01-15T06:42:00+02:00",
      EpochRise: 1642221720,
      Set: "2022-01-15T16:59:00+02:00",
      EpochSet: 1642258740,
    },
    Moon: {
      Rise: "2022-01-15T14:43:00+02:00",
      EpochRise: 1642250580,
      Set: "2022-01-16T05:35:00+02:00",
      EpochSet: 1642304100,
      Phase: "WaxingGibbous",
      Age: 13,
    },
    Temperature: {
      Minimum: {
        Value: 11.3,
        Unit: "C",
        UnitType: 17,
      },
      Maximum: {
        Value: 15.8,
        Unit: "C",
        UnitType: 17,
      },
    },
    RealFeelTemperature: {
      Minimum: {
        Value: 6.5,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 16.3,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    RealFeelTemperatureShade: {
      Minimum: {
        Value: 6.5,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 13.3,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    HoursOfSun: 4.5,
    DegreeDaySummary: {
      Heating: {
        Value: 4,
        Unit: "C",
        UnitType: 17,
      },
      Cooling: {
        Value: 0,
        Unit: "C",
        UnitType: 17,
      },
    },
    AirAndPollen: [
      {
        Name: "AirQuality",
        Value: 0,
        Category: "Good",
        CategoryValue: 1,
        Type: "Ozone",
      },
      {
        Name: "Grass",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Mold",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Ragweed",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Tree",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "UVIndex",
        Value: 3,
        Category: "Moderate",
        CategoryValue: 2,
      },
    ],
    Day: {
      Icon: 14,
      IconPhrase: "Partly sunny w/ showers",
      HasPrecipitation: true,
      PrecipitationType: "Rain",
      PrecipitationIntensity: "Light",
      ShortPhrase: "A brief morning shower or two",
      LongPhrase:
        "A brief shower or two in the morning; otherwise, times of sun and clouds",
      PrecipitationProbability: 62,
      ThunderstormProbability: 12,
      RainProbability: 62,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 14.8,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 213,
          Localized: "SSW",
          English: "SSW",
        },
      },
      WindGust: {
        Speed: {
          Value: 37,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 199,
          Localized: "SSW",
          English: "SSW",
        },
      },
      TotalLiquid: {
        Value: 1.8,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 1.8,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 1,
      HoursOfRain: 1,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 65,
      Evapotranspiration: {
        Value: 0.1,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 5467.9,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Night: {
      Icon: 40,
      IconPhrase: "Mostly cloudy w/ showers",
      HasPrecipitation: true,
      PrecipitationType: "Rain",
      PrecipitationIntensity: "Moderate",
      ShortPhrase: "Mostly cloudy, late showers",
      LongPhrase: "Mostly cloudy with showers late",
      PrecipitationProbability: 100,
      ThunderstormProbability: 20,
      RainProbability: 100,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 16.7,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 239,
          Localized: "WSW",
          English: "WSW",
        },
      },
      WindGust: {
        Speed: {
          Value: 27.8,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 253,
          Localized: "WSW",
          English: "WSW",
        },
      },
      TotalLiquid: {
        Value: 9.4,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 9.4,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 4,
      HoursOfRain: 4,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 71,
      Evapotranspiration: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 0,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Sources: ["AccuWeather"],
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=4&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=4&unit=c&lang=en-us",
  },
  {
    Date: "2022-01-16T07:00:00+02:00",
    EpochDate: 1642309200,
    Sun: {
      Rise: "2022-01-16T06:42:00+02:00",
      EpochRise: 1642308120,
      Set: "2022-01-16T17:00:00+02:00",
      EpochSet: 1642345200,
    },
    Moon: {
      Rise: "2022-01-16T15:33:00+02:00",
      EpochRise: 1642339980,
      Set: "2022-01-17T06:25:00+02:00",
      EpochSet: 1642393500,
      Phase: "WaxingGibbous",
      Age: 14,
    },
    Temperature: {
      Minimum: {
        Value: 6.8,
        Unit: "C",
        UnitType: 17,
      },
      Maximum: {
        Value: 16.3,
        Unit: "C",
        UnitType: 17,
      },
    },
    RealFeelTemperature: {
      Minimum: {
        Value: 6.4,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 12.5,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    RealFeelTemperatureShade: {
      Minimum: {
        Value: 6.4,
        Unit: "C",
        UnitType: 17,
        Phrase: "Chilly",
      },
      Maximum: {
        Value: 12.5,
        Unit: "C",
        UnitType: 17,
        Phrase: "Cool",
      },
    },
    HoursOfSun: 1.4,
    DegreeDaySummary: {
      Heating: {
        Value: 6,
        Unit: "C",
        UnitType: 17,
      },
      Cooling: {
        Value: 0,
        Unit: "C",
        UnitType: 17,
      },
    },
    AirAndPollen: [
      {
        Name: "AirQuality",
        Value: 0,
        Category: "Good",
        CategoryValue: 1,
        Type: "Ozone",
      },
      {
        Name: "Grass",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Mold",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Ragweed",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "Tree",
        Value: 0,
        Category: "Low",
        CategoryValue: 1,
      },
      {
        Name: "UVIndex",
        Value: 1,
        Category: "Low",
        CategoryValue: 1,
      },
    ],
    Day: {
      Icon: 18,
      IconPhrase: "Rain",
      HasPrecipitation: true,
      PrecipitationType: "Rain",
      PrecipitationIntensity: "Light",
      ShortPhrase: "Periods of rain",
      LongPhrase: "Periods of rain",
      PrecipitationProbability: 92,
      ThunderstormProbability: 0,
      RainProbability: 92,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 22.2,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 331,
          Localized: "NNW",
          English: "NNW",
        },
      },
      WindGust: {
        Speed: {
          Value: 31.5,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 22,
          Localized: "NNE",
          English: "NNE",
        },
      },
      TotalLiquid: {
        Value: 9.6,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 9.6,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 5.5,
      HoursOfRain: 5.5,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 84,
      Evapotranspiration: {
        Value: 0.1,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 3932.9,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Night: {
      Icon: 33,
      IconPhrase: "Clear",
      HasPrecipitation: false,
      ShortPhrase: "Clear",
      LongPhrase: "Clear",
      PrecipitationProbability: 0,
      ThunderstormProbability: 0,
      RainProbability: 0,
      SnowProbability: 0,
      IceProbability: 0,
      Wind: {
        Speed: {
          Value: 13,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 47,
          Localized: "NE",
          English: "NE",
        },
      },
      WindGust: {
        Speed: {
          Value: 33.3,
          Unit: "km/h",
          UnitType: 7,
        },
        Direction: {
          Degrees: 22,
          Localized: "NNE",
          English: "NNE",
        },
      },
      TotalLiquid: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Rain: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      Snow: {
        Value: 0,
        Unit: "cm",
        UnitType: 4,
      },
      Ice: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      HoursOfPrecipitation: 0,
      HoursOfRain: 0,
      HoursOfSnow: 0,
      HoursOfIce: 0,
      CloudCover: 5,
      Evapotranspiration: {
        Value: 0,
        Unit: "mm",
        UnitType: 3,
      },
      SolarIrradiance: {
        Value: 0,
        Unit: "W/m²",
        UnitType: 33,
      },
    },
    Sources: ["AccuWeather"],
    MobileLink:
      "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=5&unit=c&lang=en-us",
    Link: "http://www.accuweather.com/en/il/tel-aviv-port/215793/daily-weather-forecast/215793?day=5&unit=c&lang=en-us",
  },
];
//   },
// ];
